services:
  prometheus:
    image: prom/prometheus:v3.5.1
    extra_hosts:
    - "docker-host:host-gateway"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_volume:/prometheus
    ports:
      - 127.0.0.1:9090:9090

  pcap_exporter:
    build: ./pcap_exporter
    # Listens for Bitcoin P2P packets and exposes the summary metrics on an HTTP server
    command: ["pcap_exporter", "--iface", "eth0", "--filter", "port 8333", "--host", "docker-host", "--port", "8000", "--map-ips", "${HOST_IP:?error}=1.1.1.1", "--mask-ip-ports", "--dump-pcap", "--add-label", "node=${NODE_LABEL:?error}"]
    # Host network is needed, in order to have access to the eth0 interface. Yes, we also need root access.
    network_mode: "host"
    extra_hosts:
    - "docker-host:host-gateway"
    volumes:
      - ./data:/data

  python_runners:
    build: ./python_projects
    # We want the container to stop if any of the jobs stop
    command: >
      bash -c "
        trap 'kill -TERM -1' EXIT;
        # Job 1
        python ./publisher/main.py http://docker-host:8000/metrics ${PUBLISH_METRICS_REPO:?error} /run/secrets/publish_secret_key ${GITNAME:?error} ${GITEMAIL:?error} &
        # Job 2
        python ./block_exporter/main.py --host 0.0.0.0 --port 8001 &
        wait -n
        exit 1
      "
    secrets:
      - publish_secret_key
    extra_hosts:
      - "docker-host:host-gateway"

secrets:
  publish_secret_key:
    file: ${PUBLISH_SECRET_KEY_FILE:?error}

volumes:
  prometheus_volume:
