name: Pylint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      PYLINT_ARGS: "--max-line-length=120 --disable=missing-docstring"
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Lint project directories with dependencies
      run: |
        find . -name "pyproject.toml" -not -path "./.git/*" | while read toml; do
          dir=$(dirname "${toml}")
          echo "::group::Installing dependecies and linting directories"
          pip install "${dir}"
          find "${dir}" --name "*.py" -print0 | xargs -0 --no-run-if-empty \
            pylint $PYLINT_ARGS
          echo "::endgroup::"
        done
    - name: Lint standalone scripts
      run: |
        exclude_args=""
        while read toml; do
          dir=$(dirname "${toml}")
          exclude_args="${exclude_args} -path ${dir} -prune -o"
        done < <(find . -path "./.git/*" -prune -o -name pyproject.toml -print)

        # Lint files not in the directories that contain pyproject.toml
        find . -path ./.git -prune -o $exclude_args -name "*.py" -print0 \
          | xargs -0 --no-run-if-empty \
            pylint $PYLINT_ARGS
